name: Day04 GitHub Actions Learning
on:
    workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build application
        run: echo "Application build completed"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Test Application
        run: echo "Test Application completed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy application
        run: echo "Deploy success"
    


    